version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "alembic upgrade head &&
             python3 -m uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    env_file:
     - .env
    depends_on:
      - db
    networks:
      - celery-redis-network

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - celery-redis-network

#   redis:
#     image: "redis:latest"
#     ports:
#       - "6379:6379"
#     networks:
#       - celery-redis-network

#   celery:
#     build: .
#     command: celery -A tasks.app worker --uid=nobody --loglevel=info
#     volumes:
#       - .:/app
#     depends_on:
#       - redis
#     networks:
#       - celery-redis-network
#     environment:
#       - REDIS_HOST=redis-1

networks:
  celery-redis-network:
    driver: bridge
